# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='coin_four',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='coin_one',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='coin_three',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='coin_two',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
