# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180204_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='intro',
        ),
    ]
