# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articlepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
