# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 14:33
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_articlepage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
