# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_articlepage_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='press_release',
            field=models.BooleanField(default=False),
        ),
    ]
