# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 19:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_articlepage_press_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('rawhtml', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock())]),
        ),
    ]
