# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_delete_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='blue_pill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='green_pill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pill_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='red_pill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='yellow_pill',
            field=models.BooleanField(default=False),
        ),
    ]
