# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guidepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepage',
            name='length',
            field=models.CharField(blank=True, max_length=20, verbose_name='Length of guide'),
        ),
    ]
