# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_auto_20180211_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesindexpage',
            name='gettingstarted_count',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guidesindexpage',
            name='mining_count',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guidesindexpage',
            name='miscellaneous',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guidesindexpage',
            name='safety_count',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guidesindexpage',
            name='trading_count',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guidesindexpage',
            name='utilising_count',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
