# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icopage',
            name='name',
        ),
        migrations.AddField(
            model_name='icopage',
            name='pre_ico',
            field=models.BooleanField(default=False),
        ),
    ]
