# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0002_auto_20180211_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icopage',
            name='date_active',
            field=models.DateTimeField(verbose_name='Date active'),
        ),
    ]
