# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0004_auto_20180211_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icopage',
            name='date_end',
            field=models.DateTimeField(blank=True, db_index=True, verbose_name='Date end'),
        ),
    ]
