# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0006_auto_20180213_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='icopage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
