# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0008_remove_icopage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='icopage',
            name='test_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Test date'),
            preserve_default=False,
        ),
    ]
