# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0009_icopage_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icopage',
            name='test_date',
        ),
    ]
