# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0010_remove_icopage_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='icopage',
            name='featured_ico',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
