# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icos', '0011_icopage_featured_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='icopage',
            name='about',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='icopage',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='icopage',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='icopage',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='icopage',
            name='reddit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='icopage',
            name='telegram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='icopage',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
