# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 17:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepage',
            name='deposit_method',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchangepage',
            name='fees',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchangepage',
            name='withdrawal_method',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
