# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_auto_20180212_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepage',
            name='ref_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
