# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.wagtailroutablepage.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('about', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('sponsored', models.BooleanField(default=False)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('safety', models.CharField(blank=True, help_text='1=VERY SAFE, 2=MODERATELY SAFE, 3=NOT SAFE', max_length=1)),
                ('anonymity', models.CharField(blank=True, max_length=255)),
                ('ease', models.CharField(blank=True, max_length=255)),
                ('webwallet', models.BooleanField(default=False)),
                ('ios', models.BooleanField(default=False)),
                ('hardware', models.BooleanField(default=False)),
                ('android', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('linux', models.BooleanField(default=False)),
                ('chrome', models.BooleanField(default=False)),
                ('macos', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WalletPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wallets.WalletPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets_walletpagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('header_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='walletpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Supported coins', through='wallets.WalletPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
